### ISSUE TITLE
Overriding $urlAuthorize and $urlAccessToken

### ISSUE THREAD

**Issue by jamesmacwhite** [LoicBoursin/oauth2-microsoft-graph#3]
Depending on the app registration, the common endpoints are not valid for use and instead, you need to use a `urlAuthorize` and `urlAccessToken` URL value with your Microsoft Entra Tenant ID.

* Authorize URL - https://login.microsoftonline.com/{{TenantID}}/oauth2/v2.0/authorize
* Access Token URL - https://login.microsoftonline.com/{{TenantID}}/oauth2/v2.0/token

For this purpose it would be good to be able have the ability to override these potentially.

Here's what happens when try and use the common endpoints with a single tenant app registration:

> AADSTS50194: Application 'xxxxxxxxxxxxxxxxxxxxxxxxxx'(APP NAME) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant. Trace ID: 36a86449-54e2-49d6-8852-4cf8e461bd00 Correlation ID: 1c1457e6-5047-4ed7-9449-95f49b8277cf Timestamp: 2023-12-21 18:37:48Z

In my case I am using your provider with another OAuth solution, so I am not directly extending it, but providing it as  providerClass which is being referenced.

**Comment by LoicBoursin** [comment]
Can you precise with examples how you use this provider with the other OAuth solution? I'm not sure to understand how you want to override these. It may be possible to extends the parent constructor of the `Microsoft` class in this library to add more options.

**Comment by jamesmacwhite** [comment]
It's a bit bespoke because it's for a specific PHP CMS (Craft CMS), but best example is the plugin being used and how it passed in a LeagueProvider class:

https://github.com/venveo/craft-oauthclient?tab=readme-ov-file#providers

The issue is I think, that the Provider class of this plugin does not expose the Access Token URL, it does expose Authorize URL, which can be overridden, so it might be on the plugin side.

**Comment by LoicBoursin** [comment]
In your example:

```php
public static function getProviderClass(): string
    {
        // Return the class name for the league provider
        return LeagueProvider::class;
    }
```

You can create your own provider that extends the `Microsoft` provider in this library. By extending it, it will allow you to extend any class property such as `$urlAuthorize` and `$urlAccessToken`. Then use your own provider in the `getProviderClass()` method of your CMS.

**Comment by jamesmacwhite** [comment]
Thanks! That's what I've ended up doing. The extra layer of abstraction was confusing, but I've implemented this:

```php
<?php

namespace example\venveo\provider;

use Craft;
use venveo\oauthclient\base\Provider;

class MicrosoftGraphApi extends Provider
{
	/**
	 * @inheritDoc
	 */
	public static function displayName(): string
	{
		return Craft::t('my-module', 'Microsoft Graph API');
	}

	public static function getProviderClass(): string
	{
		return MyCustomMicrosoftProvider::class;
	}
}
```

```php
<?php

namespace example\microsoft\provider;

use LoicBoursin\OAuth2\Client\Provider\Microsoft as MicrosoftProvider;

class MyCustomMicrosoftProvider extends MicrosoftProvider
{
	protected string $urlAuthorize = 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/authorize';
	protected string $urlAccessToken = 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/token';
}
```

Thanks for adding this OAuth2 League provider, very useful, to get up and running with the Microsoft Graph API!

**Comment by LoicBoursin** [comment]
Glad you found it useful! Since your issue is resolved, I'm closing it.

**Comment by jamesmacwhite** [comment]
Sure thing, I don't know if it's worth a note in your docs re: the default common endpoints. In many cases the specific tenant ID is likely needed if multi-tenant is not enable on the app registration. Of course, as you've shown extending the library allows you to modify the URL auth and token endpoints, but possibly worth highlighting?

**Comment by LoicBoursin** [comment]
Yes, I'll add a part about extending to the README!

**Comment by LoicBoursin** [comment]
Documentation was updated in https://github.com/LoicBoursin/oauth2-microsoft-graph/pull/4

**Comment by jamesmacwhite** [comment]
Awesome! Thanks for the quick work, hope it helps others!
